import {
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLeetcode,
  IconBrandLinkedin,
  IconBrandYoutube,
} from "@tabler/icons-react";
const Info = {
  name: "Abdullah Abbasi",
  stack: [
    "Frontend Developer",
    "Backend Developer",
    "Competitive Programmer",
    "Freelancer",
    "Open Source Contributor",
  ],
  bio: "I'm a passionate web developer specialized in crafting efficient and scalable solutions, deliver top-notch web applications, and provide freelance services that exceed client expectations. Let's connect and create something amazing together!",
};

const ProjectInfo = [
  {
    title: "Movix",
    desc: "Explore my portfolio project: a sophisticated movie & TV streaming platform built with React.js, Redux.js & Sass/SCSS. Seamlessly integrated with the TMDB API, dive into a vast library of titles, enriched with comprehensive metadata, ratings, trailers & genres. Offering an intuitive user experience, visitors can effortlessly navigate through the cinematic landscape, discovering their favorite content with ease. With its sleek design and robust features, including advanced search algorithms and interactive elements, users can elevate their streaming experience. Whether you're a cinephile or a casual viewer, embark on an immersive journey through the world of cinema and television. Discover endless entertainment possibilities and unlock the magic of storytelling with my groundbreaking portfolio project.",
    image: "movix.png",
    live: true,
    technologies: ["React", "Tailwind", "Redux", "TMDB API", "Infinite Scroll"],
    link: "https://digitalmovix.com",
    github: "https://github.com/abdullah-dot-programmer/movix/",
  },
  {
    title: "TechChow",
    desc: "TechChow is a sophisticated and user-friendly technology news and review platform designed to provide the latest updates, in-depth analyses, and comprehensive reviews of cutting-edge gadgets and software. Developed with a focus on delivering high-quality, reliable information, TechChow serves tech enthusiasts, professionals, and everyday users alike. The website features a responsive design, ensuring a seamless browsing experience across all devices.",
    image: "techchow.png",
    live: true,
    technologies: ["HTML", "CSS", "JQuery", "JavaScript"],
    link: "https://techchow.net",
    github: "https://github.com/abdullah-dot-programmer/techchow/",
  },
  {
    title: "Cara-Ecommerce",
    desc: "I have created ChicWearHub E-Commerce website as a project to showcase my expertise in Frontend development. I utilize the modern technologies HTML, CSS and JavaScript to make this website visually appealing and eyeCatchy. The website design is simple and attractive which showcases my skills in Web Development. The website is responsive, funcional and is accessible in all devices.",
    image: "cara.png",
    live: true,
    technologies: ["HTML", "CSS", "JavaScript", "Resposive Design"],
    link: "https://github.com/Code-Mars/Spotify-Clone",
    github: "https://github.com/abdullah-dot-programmer/ChicWearHub",
  },
  {
    title: "MERN-Blog",
    desc: "I successfully developed a robust blogging platform that includes essential features such as user authentication, post creation, commenting, and tagging. The platform allows users to register, log in, and manage their accounts securely, while providing a user-friendly interface for creating and publishing blog posts with titles, content, images, and tags. Additionally, users can engage in discussions through a commenting system, and categorize their posts using dynamic tagging for improved content discovery.",
    image: "mern-blog.png",
    live: true,
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Tailwind",
      "JWT",
      "REST API",
    ],
    link: "https://mern-blog-z6za.onrender.com/",
    github: "https://github.com/Code-Mars/mern-blog",
  },
  {
    title: "Gymso Fitness",
    desc: "I have created Gymso Fitness Website using HTML CSS and JavaScript. It is modern and simple disign that is resposnive and can be accessible on different screen sizes. It gives you the impression of my design and development abilities. ",
    image: "gymso.png",
    live: true,
    technologies: ["HTML", "CSS", "JavaScript", "Resposnive Design"],
    link: "https://abdullah-dot-programmer.github.io/Gymso-Fitness/",
    github: "https://github.com/Code-Mars/Gymso-Fitness/",
  },
  {
    title: "Job-Portal",
    desc: "Developed a feature-rich Job Portal using the MERN stack (MongoDB, Express.js, React, Node.js). The application enables users to sign up, create profiles, and search for jobs based on role and location. Authentication is handled with JWT, with secure cookies stored using httpOnly and SameSite configurations. Implemented user role-based access control for job seekers and employers, allowing employers to post jobs and manage applications. Deployed on Render with CORS configured for cross-domain requests, ensuring secure and seamless operation across frontend and backend services.",
    image: "jobPortal.png",
    live: true,
    technologies: [
      "React",
      "Tailwind",
      "Express",
      "Nodejs",
      "MongoDB",
      "Nodemailer",
      "flowbite react",
    ],
    link: "https://job-portal-frontend-hy4k.onrender.com/",
    github: "https://github.com/abdullah-dot-programmer/Job-Portal",
  },
];

const SkillInfo = [
  {
    title: "Frontend",
    skills: [
      "HTML",
      "CSS",
      "SASS",
      "JavaScript",
      "React JS",
      "Redux",
      "Tailwind CSS",
      "GSAP",
      "Bootstrap",
    ],
  },
  {
    title: "Backend",
    skills: ["Node JS", "Express JS", "MongoDB", "Firebase"],
  },
  {
    title: "Languages",
    skills: ["C", "C++", "JavaScript", "TypeScript"],
  },
  {
    title: "Tools",
    skills: ["Git", "Github", "VS Code", "Postman", "MongoDB Compass"],
  },
];
const socialLinks = [
  { link: "https://github.com/abdullah-dot-programmer", icon: IconBrandGithub },
  { link: "https://www.linkedin.com/", icon: IconBrandLinkedin },
  { link: "https://www.instagram.com/", icon: IconBrandInstagram },
  { link: "https://www.youtube.com/@globalpowers9", icon: IconBrandYoutube },
  { link: "https://www.leetcode.com/", icon: IconBrandLeetcode },
];

const ExperienceInfo = [
  {
    role: "Frontend Developer Internship",
    company: "AdEngineers",
    date: "Oct 2023 - Mar 2024",
    desc: "I led frontend development with React creating scalable microservices and interfaces. I optimized performance by integrating frontend and backend, and enhanced security with RESTful APIs. Collaborating in agile teams, I fostered innovation and efficiency for top-quality solutions.",
    skills: [
      "React JS",
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind CSS",
      "Bootstrap",
    ],
  },
  {
    role: "Backend Developer Internship",
    company: "AdEngineers",
    date: "Apr 2024 - Sep 2024",
    desc: "As a backend developer, I primarily focused on the server-side of web applications. This involves building and maintaining the infrastructure that powers the application, including databases, APIs, and server-side logic. My responsibilities  included designing and implementing database schemas, developing APIs to communicate with the frontend, writing server-side code to handle business logic, and ensuring the application's performance, scalability, and security. I worked closely with frontend developers to create seamless user experiences and collaborated with other team members to deliver high-quality software.",
    skills: ["Node JS", "Express JS", "MongoDB", "Postman", "Mongoose"],
  },
];
const Slugs = [
  "typescript",
  "spring",
  "javascript",
  "dart",
  "java",
  "react",
  "angular",
  "flutter",
  "android",
  "html5",
  "css3",
  "springboot",
  "mongodb",
  "selenium",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "mysql",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
];
export { Info, ProjectInfo, socialLinks, SkillInfo, ExperienceInfo, Slugs };
